### ISSUE TITLE
Best way to update map to latest TerriaJS

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/map#2]
This is totally exposing my lack of knowledge about JS, but having cloned this "map" repo, what is the appropriate way to bring it up-to-date with the latest release in the terriajs repo?   (e.g I'd like to try out the CSW capabilities)

**Comment by kring** [comment]
There are a few options.  For development, the easiest is usually to use the `npm link` feature, which lets the `map` app use any local version of TerriaJS that you like.  Instructions for setting that up are here:
https://github.com/NICTA/nationalmap/wiki/Developers%27-Handbook#building-national-map-against-a-modified-terriajs

The other option is to modify the `terriajs` entry in map's `package.json`.  You can update it to the latest version, which is 1.0.36 as of this writing.  But unfortunately the CSW support will be in 1.0.37 which I haven't yet published to npm yet.  But in addition to npm versions, package.json can reference git repos.  So change it to:

```javascript
"terriajs": "git://github.com/TerriaJS/terriajs#master"
```

You can replace `master` with any branch you like.  Then, run `npm install` and npm will pull down that branch from GitHub.  You may need to run `npm install` twice due to a [bug in npm](https://github.com/TerriaJS/terriajs/wiki/Problems-and-Solutions#cannot-find-module-terriajs-cesiumwwwroot).

**Comment by rsignell-usgs** [comment]
I used the option of specifying the github master branch in the `package.json` and then doing `npm install` and `npm restart`.   Worked fine!
