### ISSUE TITLE
Problem installing map on windows 7

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/map#4]
I followed the instructions here for installing TerriaJS on windows:
https://github.com/TerriaJS/terriajs/wiki/Deploying-and-building-TerriaJS

but when I try typing `npm install` from the `Node.js` command prompt, I get:
```
C:\Users\rsignell\Downloads\map-usgs>npm install
npm WARN package.json terriajs-map@0.0.1 No license field.
-
> terriajs@1.0.39 postinstall C:\Users\rsignell\Downloads\map-usgs\node_modules\
terriajs
> bash -c "if [ ! -d "./wwwroot/build" ]; then gulp prepare-cesium; fi"

C:\Users\rsignell\Downloads\map-usgs\node_modules\glob-all\node_modules\glob\nod
e_modules\minimatch\minimatch.js:579
});
 ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\rsignell\Downloads\map-usgs\node_modules\glo
b-all\node_modules\glob\glob.js:44:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! terriajs@1.0.39 postinstall: `bash -c "if [ ! -d "./wwwroot/build" ]; t
hen gulp prepare-cesium; fi"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terriajs@1.0.39 postinstall script 'bash -c "if [ ! -d ".
/wwwroot/build" ]; then gulp prepare-cesium; fi"'.
npm ERR! This is most likely a problem with the terriajs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash -c "if [ ! -d "./wwwroot/build" ]; then gulp prepare-cesium; fi"
```
Looks like the postinstall is expecting bash...

**Comment by kring** [comment]
Yes, you need bash.  Git for Windows includes bash - that's the one I use.

**Comment by Chirag19** [comment]
How to install and use bash in windows-10?

**Comment by YashSoniJi** [comment]
In case if anyone face problem like given below while installing tarriamap in windows 10
the best option is to replace your node version to 10.18.0 and npm version 16.13.4. It is because Node version above 10 does not have support for terria.
Remember to use git bash instead of using command prompt for cloning the repository.
-select a empty folder where you want to clone the repo.
-open bash.
-type "git clone https://github.com/TerriaJS/TerriaMap.git"
-cd TerriaMap
-npm install
-npm run gulp
-npm start
Then, open a web browser on http://localhost:3001 to use TerriaMap.

for more information regarding installation you can visit
https://docs.terria.io/guide/getting-started/

cd TerriaMap

PTS-PC-111_USR02@PTS-PC-115 MINGW64 /e/PTS/Project/TerriaMap (master)
$ npm install

> husky@2.7.0 install E:\PTS\Project\TerriaMap\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done
husky > Like husky? You can support the project on Patreon:
husky > https://www.patreon.com/typicode ≡ƒÉò

> node-sass@4.13.0 install E:\PTS\Project\TerriaMap\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\PTS-PC-111_USR02\AppData\Roaming\npm-cache\node-sass\4.13.0\win32-x64-72_binding.node

> core-js@2.6.11 postinstall E:\PTS\Project\TerriaMap\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> terriajs-cesium@1.71.1 postinstall E:\PTS\Project\TerriaMap\node_modules\terriajs-cesium
> bash -c "if [ ! -d "./wwwroot/build" ]; then gulp -f gulpfile.cjs terria-prepare-cesium; fi"


> ejs@2.7.4 postinstall E:\PTS\Project\TerriaMap\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> node-sass@4.13.0 postinstall E:\PTS\Project\TerriaMap\node_modules\node-sass
> node scripts/build.js

Binary found at E:\PTS\Project\TerriaMap\node_modules\node-sass\vendor\win32-x64-72\binding.node
Testing binary
Binary is fine

> terriajs@7.11.6 postinstall E:\PTS\Project\TerriaMap\node_modules\terriajs
> gulp post-npm-install

[12:10:56] Using gulpfile E:\PTS\Project\TerriaMap\node_modules\terriajs\gulpfile.js
[12:10:56] Starting 'post-npm-install'...
[12:10:56] Starting 'copy-cesium-assets'...
[12:10:56] 'copy-cesium-assets' errored after 1.14 ms
[12:10:56] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in E:\PTS\Project\TerriaMap\node_modules\terriajs-cesium\package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at E:\PTS\Project\TerriaMap\node_modules\terriajs\gulpfile.js:78:33
    at copy-cesium-assets (E:\PTS\Project\TerriaMap\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at asyncRunner (E:\PTS\Project\TerriaMap\node_modules\async-done\index.js:55:18)
[12:10:56] 'post-npm-install' errored after 2.52 ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terriajs@7.11.6 postinstall: `gulp post-npm-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terriajs@7.11.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PTS-PC-111_USR02\AppData\Roaming\npm-cache\_logs\2020-07-24T06_41_01_317Z-debug.log
